services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: siaes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  app:
    build: .
    container_name: siaes-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/siaes
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: my-secret-key
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-net

networks:
  app-net:

volumes:
  postgres_data:
